name: Playwrightium Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  playwrightium_local:
    env:
      DISPLAY: :0
    name: 'Playwrightuim local Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress
      - name: Run tests
        run: xvfb-run mvn test -Dtest=org.brit.test.selenide.local.**.*
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          include_passed: true
  playwrightium_selenoid:
    name: 'Playwrightium remote tests'
    runs-on: ubuntu-latest
    steps:
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Install
        run: mvn -B install -DskipTests --no-transfer-progress
      - name: Run tests
        run: mvn test -Dtest=org.brit.test.selenide.remote.**.*
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
          include_passed: true
